'use strict';window.StackExchange={};function CTIsPlayback(){try{return parent&&parent.WebPlayer}catch(g){return!1}}!CTIsPlayback()&&top!=self&&(top.location.replace(document.location),alert("For security reasons, framing is not allowed; click OK to remove the frames."));
StackExchange.init=function(){var g=function(c){if(!window.jQuery)if("complete"!=document.readyState)setTimeout(function(){g(c)},1E3);else{var d=document.createElement("div");d.id="noscript-padding";var a=document.createElement("div");a.id="noscript-warning";a.innerHTML=c+" requires external JavaScript from another domain, which is blocked or failed to load.";document.body.insertBefore(d,document.body.firstChild);document.body.appendChild(a)}},c=function(){$(document).keyup(function(c){27==c.which&&
($("#lightbox:not(.no-esc-remove), .error-notification, .popup, .share-tip, .esc-remove").fadeOutAndRemove(),$(".esc-hide").fadeOut(),window.genuwine&&genuwine.isVisible()&&genuwine.click(),window.profileLink&&profileLink.hide())})},e=function(){var c=$("#hlinks"),d=$("#search input[name=q]"),a=d.width(),e=2.5*a,g,h=function(a){d.queue("expand",a)},j=!1,k=!("placeholder"in document.createElement("input"));k&&!StackExchange.options.isMobile&&(""==d[0].value&&(d[0].value="search"),d.bind({focus:function(){"search"==
this.value&&(this.value="")}}));d.keydown(function(a){if(j||46>a.keyCode&&8!=a.keyCode&&32!=a.keyCode)return!0;j=!0;clearTimeout(g);d.clearQueue("expand");h(function(a){d[0].placeholder="";c.fadeOut(100,a)});h(function(a){d.animate({width:e,"max-width":e},100,a)});h(function(){0==d.parent().find(".search-prompt").length&&d.before('<span class="search-prompt">search:</span>')});3==d.queue("expand").length&&d.dequeue("expand")}).focusout(function(){g=setTimeout(function(){h(function(a){d.parent().find(".search-prompt").remove();
a()});h(function(c){d.animate({width:a,"max-width":a},100,c)});h(function(a){k&&""==d[0].value&&(d[0].value="search");d[0].placeholder="search";c.fadeIn(100,a)});3==d.queue("expand").length&&d.dequeue("expand");j=!1},200)});$("#search").keydown(function(a){if(13==a.which&&a.ctrlKey&&d.val())return window.open("/search?q="+encodeURIComponent(d.val()),"_newtab"),!1})};return function(f){StackExchange.options=f;var d=f.serverTime-(new Date).getTime()/1E3;g(f.site.name);$.ajaxSetup({cache:!1});StackExchange.init.createJqueryExtensions();
$(function(){c();e();StackExchange.using(StackExchange.options.user.isAnonymous?"anonymous":"loggedIn",function(){StackExchange.initialized.resolve()},!0);StackExchange.ready(function(){genuwine.init(f.user.accountId||null,f.user.inboxUnviewedCount);f.user.messages&&StackExchange.notify.showMessages(f.user.messages,f.isMobile);f.site.globalAuthDisabled||(!f.site.isChildMeta&&f.user.isAnonymous&&gauth.checkStackAuth(f.stackAuthUrl),gauth.informStackAuth(f.stackAuthUrl));f.user.isAnonymous?StackExchange.notify.showFirstTime(f.site.description):
profileLink.init(f.user.gravatar,f.isMobile,f.user.profileUrl+"?tab=activity",d);f.enableUserHovercards&&StackExchange.usermenu.init();StackExchange.tagPreferences?StackExchange.tagPreferences.init():StackExchange.tagmenu.init()})})}}();
StackExchange.debug={log:function(){},init:function(){this.log=function(g){$(function(){var c=$("#debug-messages");c.length||(c=$("<div id='debug-messages' style='text-align:left;position:fixed;top:50px;left:50px;z-index:1000;background:white;border:2px solid black;width:300px;padding:10px;' />").append($("<span style='cursor:pointer;color:#999'>(close debug messages)</span>").click(function(){$("#debug-messages").remove()})).appendTo("body"));$("<div style='margin-top:10px' />").text(g).appendTo(c)})}}};
StackExchange.initialized=$.Deferred();StackExchange.ready=function(g){StackExchange.initialized.done(g)};
(function(){var g={prettify:"prettify-full.js",pseudoModerator:"moderator.js",anonymous:"full-anon.js",loggedIn:"full.js",inlineEditing:"full.js",editor:"wmd.js",autocomplete:"third-party/jquery.autocomplete.min.js",tagAutocomplete:"tageditor.js",tagEditor:"tageditornew.js",mobile:"mobile.js",help:"help.js",inlineTagEditing:"inline-tag-editing.js",mathjaxEditing:"mathjax-editing.js",revisions:"revisions.js",suggestedEdits:"suggested-edits.js",mockups:"mockups.js"},c={},e={},f,d={},a=function(a,c){return function(d){var e=
a[d];e||(e=a[d]=c(d));return e}},n=function(a){var a=c[a],d,e=$.Deferred(),f=$.when(e),g;if(a)for(d=0;d<a.length;d++)(g=a[d].call(null))&&$.isFunction(g.promise)&&(f=$.when(f,g));e.resolve();return f},i=function(){if(!f){var a=$("script[src*='/stub.js']:first");0==a.length?(StackExchange.debug.log("couldn't figure out location of stub.js"),f="/content/js/"):f=a.attr("src").replace(/\/stub\.js.*$/,"/")}return f},h=function(a){var c=d["js/"+a];return!c?(StackExchange.debug.log("no cache breaker for "+
a),""):"?v="+c},j=function(a){a=g[a];return!a?$.Deferred().reject().promise():k(a)},k=a({},function(a){var c=$.Deferred(),d=document.createElement("script");d.async="async";d.type="text/javascript";d.src=i()+a+h(a);d.onload=d.onreadystatechange=function(a,e){if(!d.readyState||/loaded|complete/.test(d.readyState))e?c.reject():c.resolve()};d.onerror=function(){c.reject()};$("head")[0].appendChild(d);return c.promise()}),l=a({},function(a){function c(){(e=StackExchange[a])?n(a).done(function(){d.resolve()}):
0<f?(f--,StackExchange.debug.log("retrying "+a),setTimeout(c,20)):(StackExchange.debug.log("object "+a+" not available although file was loaded"),d.reject())}var d=$.Deferred(),e=StackExchange[a],f=3;e?d.resolve():j(a).done(c).fail(d.reject);return d.promise()}),a=function(a,c,d){var e=l(a);d||(e=$.when(e,StackExchange.initialized));e.done(function(){c()}).fail(function(){StackExchange.debug.log("failed to provide object "+a)});return e};a.setCacheBreakers=function(a){for(var c in a)a.hasOwnProperty(c)&&
(d[c]=a[c])};StackExchange.using=a;StackExchange.ifUsing=function(a,d,f){if("undefined"!==typeof f){if(e["u_"+f])return;e["u_"+f]=!0}StackExchange[a]?d():((f=c[a])||(f=c[a]=[]),f.push(d))}})();String.prototype.format=function(){var g=this.toString();if(!arguments.length)return g;var c="string"==typeof arguments[0]?arguments:arguments[0],e;for(e in c)g=g.replace(RegExp("\\{"+e+"\\}","gi"),c[e]);return g};
String.prototype.truncate=function(g,c){var e=this.toString();g&&e.length>g&&(e=e.substr(0,g)+c);return e};
StackExchange.init.createJqueryExtensions=function(){var g=StackExchange.helpers;$.fn.extend({fadeOutAndRemove:function(){return this.each(function(){var c=$(this);c.fadeOut("fast",function(){c.trigger("removing").remove()})})},charCounter:function(c){return this.each(function(){var e=c.target?$(c.target):$(this).parents("form").find("span.text-counter"),f=this;$(this).bind("blur focus keyup paste",g.DelayedReaction(function(){var d=c.min,a=c.max,g=c.setIsValid||function(){},i=f.value?f.value.length:
0,h=i>0.8*a?"supernova":i>0.6*a?"hot":i>0.4*a?"warm":"cool",j="";0==i?(j="enter at least "+d+" characters",g(!1)):i<d?(j=d-i+" more to go...",g(!1)):(j=a-i+" character"+(1!=a-i?"s":"")+" left",g(i<=a));e.text(j);e.hasClass(h)||e.removeClass("supernova hot warm cool").addClass(h)},100,{sliding:!0}).trigger)})},selectRange:function(c,e){return this.each(function(){if(this.setSelectionRange)this.focus(),this.setSelectionRange(c,e);else if(this.createTextRange){var f=this.createTextRange();f.collapse(!0);
f.moveEnd("character",e);f.moveStart("character",c);f.select()}})},addSpinner:function(c){return this.each(function(){g.addSpinner(this,c)})},addSpinnerAfter:function(c){return this.each(function(){$(this).after(g.getSpinnerImg(c))})},removeSpinner:function(){return this.each(function(){$(this).find("img.ajax-loader").remove()})},showErrorPopup:function(c,e,f){return this.each(function(){g.showErrorPopup(this,c,e,f)})},center:function(){var c=this.parent();"static"===c.css("position")&&(c=c.offsetParent());
var c=c.offset(),e=$(window);this.css("position","absolute");this.css("top",(e.height()-this.height())/2+e.scrollTop()-c.top+"px");this.css("left",(e.width()-this.width())/2+e.scrollLeft()-c.left+"px");return this},helpOverlay:function(){g.bindHelpOverlayEvents(this);return this},hideHelpOverlay:function(){g.hideHelpOverlay(this);return this},enable:function(){0==arguments.length||arguments[0]?this.removeAttr("disabled").css("cursor","pointer"):this.attr("disabled","disabled").css("cursor","default");
return this},disable:function(){return this.enable(!1)},loadPopup:function(c){var e=this;e.addSpinnerAfter({padding:"0 3px"});$.ajax({type:"GET",url:c.url,dataType:"html",success:function(f){var d=$(f);d.find(".popup-actions-cancel, .popup-close a").click(function(){d.fadeOutAndRemove()});d.find("input:radio[disabled=disabled] + label.action-label").addClass("action-disabled");c.hideDescriptions&&d.find("ul.action-list > li:not(.action-selected) .action-desc").hide();f=d.find("input:radio:not(.action-subform input)");
f.closest("li").bind("hide-action",function(){var a=$(this),d=".action-subform"+(c.hideDescriptions?", .action-desc":"");a.removeClass("action-selected").find(d).slideUp("fast")}).bind("show-action",function(){var a=$(this);a.hasClass("action-selected")||(a.siblings(".action-selected").trigger("hide-action"),a.addClass("action-selected").find(".action-subform").slideDown("fast",function(){c.subformShow&&c.subformShow($(this));if(c.subformFocusInput){var a=$(this).find("input[type=text], textarea").not(".actual-edit-overlay").eq(0);
a.length&&a.focus()}}),c.hideDescriptions&&a.find(".action-desc").slideDown("fast"),c.actionSelected&&c.actionSelected(a),d.find(".popup-submit").enable())});f.click(function(){$(this).closest("li").trigger("show-action")});d.appendTo(e.parent());c.loaded&&c.loaded(d);f=function(){};if(c.subformShow){var a=d.find("li.action-selected .action-subform");0<a.length&&(f=function(){a.each(function(){c.subformShow($(this))})})}c.dontCenter||d.center().fadeIn("fast",f)},error:function(){e.parent().showErrorPopup("Unable to load popup - please try again")},
complete:g.removeSpinner});return e},normalizeRadioTextareaBehaviour:function(){this.mouseup(function(){var c=$("#"+$(this).closest("label").attr("for"));c&&c.length&&!1===c.is(":checked")&&c.attr("checked",!0);var e=$(this);setTimeout(function(){e.focus()},1)});return this}})};
StackExchange.helpers=function(){function g(a,c,d){for(var e=0;e<d.length;e++){var g=d[e];try{if(/\*/.test(g))for(var k=0;4>k;k++){var l=g.replace(/\*/g,f[k]),o=a.css(l);c.css(l,o)}else c.css(g,a.css(g))}catch(p){}}}function c(a,c,d,e){if(a.is(":visible")){var f=$.browser.msie?0:0.4;d()?(a.css("opacity",f+(e?0.2:0)),a.addClass("edit-field-overlayed"),d=a.prev(".actual-edit-overlay"),0==d.length&&(e=a.parent().find("span.edit-field-overlay").text(),d=a.width(),f=a.height(),d=a.clone().prop("className",
"actual-edit-overlay").attr("name",null).attr("id",null).attr("disabled","disabled").css({position:"absolute",backgroundColor:"white",color:"black","-webkit-text-fill-color":"black",opacity:1,width:d,height:f}),d.is("textarea,input")?(d.val(e),g(c,d,["line-height"])):d.text(e).css("line-height",f+"px").prepend("&nbsp;"),g(c,d,["font-family","font-size","text-align"]),g(a,d,["border-*-style","border-*-color","border-*-width"]),a.css({zIndex:1,position:"relative"}),d.insertBefore(a),e=a.offset().top-
d.offset().top,0!=e&&(c=parseInt(d.css("margin-top")),e=c+e,a.is("textarea")||(e=parseInt(d.prevAll(":visible").eq(0).css("margin-bottom"))+c),d.css("margin-top",e)),a=a.offset().left-d.offset().left,0!=a&&(c=parseInt(d.css("margin-left")),d.css("margin-left",c+a)))):a.css("opacity",1).css("filter","").removeClass("edit-field-overlayed")}}function e(a,d){$(a).find("input[type='submit']").prop("disabled",d)}var f=["left","right","top","bottom"],d={genericBindOverlayEvents:function(a,e,f){StackExchange.options.isMobile||
e.bind("keydown contextmenu",function(){d.hideHelpOverlay(a)}).focus(function(){c(a,e,f,!0)}).blur(function(){c(a,e,f)}).each(function(){c(a,e,f)})},bindHelpOverlayEvents:function(a){a.each(function(){var a=$(this);d.genericBindOverlayEvents(a,a,function(){return""===a.val()})})},hideHelpOverlay:function(a){a.css("opacity",1);a.css("filter","");a.removeClass("edit-field-overlayed")},onClickDraftSave:function(a){$(a).click(function(){var a=this.href;StackExchange.cardiologist.ensureDraftSaved(function(){window.onbeforeunload=
null;window.location.href=a});return!1});return!0},showErrorPopup:function(a,d,c,e){$(".error-notification").remove();var f=$('<div class="error-notification supernovabg"><h2>'+d+"</h2>"+(c?"":'<span class="error-close">(click on this box to dismiss)</span>')+"</div>"),g=function(){f.fadeOutAndRemove();e&&e()};$(a).append(f);f.click(g).fadeIn("fast");setTimeout(g,c?Math.max(2500,40*d.length):3E4)},removeErrorPopup:function(){$(".error-notification").fadeOutAndRemove()},addSpinner:function(a,c){$(a).append(d.getSpinnerImg(c))},
getSpinnerImg:function(a){var d=$('<img class="ajax-loader" src="/content/img/progress-dots.gif" title="loading..." alt="loading..." />');a&&d.css(a);return d},removeSpinner:function(){$("img.ajax-loader").remove()},enableSubmitButton:function(a){e(a,!1)},disableSubmitButton:function(a){e(a,!0)},loadTicks:function(a){var d;d=a?a.find(".edit-block"):$(".edit-block");0==d.find("input[name=i1l]").length&&!d.data("loading-ticks")&&(d.data("loading-ticks",!0),$.ajax({url:"/questions/ticks",cache:!1,success:function(a){d.append("<input type='hidden' name='i1l' value='"+
a+"' />")},complete:function(){d.data("loading-ticks",!1)}}))},showFancyOverlay:function(a){var a=a||{},d=$("#overlay-header"),c=a.message||"",e=$.browser.msie?{background:"#fff",opacity:0}:{};!1!==a.showClose&&(c+='<br><a class="close-overlay">close this message</a>');d.html(c).css(e).animate({opacity:"1",height:"show"},"slow",a.complete).find(".close-overlay").click(function(){d.animate({opacity:"0",height:"hide"},"fast")})},DelayedReaction:function(a,d,c){var c=c||{},e,f,g=c.always,l=function(){e=
null;a.apply(null,f)};return{trigger:function(){f=arguments;g&&g.apply(null,f);e?c.sliding&&(clearTimeout(e),e=setTimeout(l,d)):e=setTimeout(l,d)},cancel:function(){e&&(clearTimeout(e),e=null)}}},fireAndForget:function(a){$.ajax({type:"POST",url:a,async:!0})}};return d}();
function prepareEditor(g){var c=g.postfix||"",e=function(){setTimeout(function(){StackExchange.editor.initIfShown(g)},1)};if(g.onDemand){for(var f="bold-button,italic-button,spacer1,link-button,quote-button,code-button,image-button,spacer2,olist-button,ulist-button,heading-button,hr-button,spacer3,undo-button,redo-button".split(","),d=$('<ul id="wmd-button-row'+c+'" class="wmd-button-row" />').appendTo(".wmd-button-bar"),a=0,n=0;n<f.length;n++){var i=f[n],h=/spacer/.test(i),i=$("<li id='wmd-"+i+c+
"' />").prop("className","wmd-"+(h?"spacer":"button")).css("left",25*n).appendTo(d);$("<span />").css("background-position",a+"px -20px").appendTo(i);h||(a-=20)}var j=!1;$("#wmd-input, #title, #tagnames, #edit-comment, #m-address, #display-name").one("focus click keydown",function(){j||(j=!0,d.addSpinner({"float":"right"}),StackExchange.using("editor",function(){d.remove();g.autoShowMarkdownHelp&&(g.immediatelyShowMarkdownHelp=!0);e()}))})}else StackExchange.using("editor",e)}
StackExchange.switchMobile=function(g,c){$.post("/mobile/"+g,{returnurl:c},function(c){window.location=c})};
jQuery.cookie=function(g,c,e){if("undefined"!=typeof c){e=e||{};null===c&&(c="",e.expires=-1);var f="";if(e.expires&&("number"==typeof e.expires||e.expires.toUTCString))"number"==typeof e.expires?(f=new Date,f.setTime(f.getTime()+864E5*e.expires)):f=e.expires,f="; expires="+f.toUTCString();var d=e.path?"; path="+e.path:"",a=e.domain?"; domain="+e.domain:"",e=e.secure?"; secure":"";document.cookie=[g,"=",encodeURIComponent(c),f,d,a,e].join("")}else{c=null;if(document.cookie&&""!=document.cookie){e=
document.cookie.split(";");for(f=0;f<e.length;f++)if(d=jQuery.trim(e[f]),d.substring(0,g.length+1)==g+"="){c=decodeURIComponent(d.substring(g.length+1));break}}return c}};jQuery.expr[":"].regex=function(g,c,e){var c=e[3].split(","),f=/^(data|css):/,e=c[0].match(f)?c[0].split(":")[0]:"attr",f=c.shift().replace(f,"");return RegExp(c.join("").replace(/^\s+|\s+$/g,""),"ig").test(jQuery(g)[e](f))};
$.extend($.expr[":"],{containsExact:function(g,c,e){return $.trim(g.innerHTML.toLowerCase())===e[3].toLowerCase()},containsExactCase:function(g,c,e){return $.trim(g.innerHTML)===e[3]},containsRegex:function(g,c,e){c=/^\/((?:\\\/|[^\/])+)\/([mig]{0,3})$/.exec(e[3]);return RegExp(c[1],c[2]).test($.trim(g.innerHTML))}});
$.extend({URLEncode:function(g){for(var c="",e=0,g=g.toString(),f=/(^[a-zA-Z0-9_.]*)/;e<g.length;){var d=f.exec(g.substr(e));null!=d&&1<d.length&&""!=d[1]?(c+=d[1],e+=d[1].length):(" "==g[e]?c+="+":(d=g.charCodeAt(e).toString(16),c+="%"+(2>d.length?"0":"")+d.toUpperCase()),e++)}return c},URLDecode:function(g){for(var c,e=/(%[^%]{2})/;null!=(m=e.exec(g))&&1<m.length&&""!=m[1];)b=parseInt(m[1].substr(1),16),c=String.fromCharCode(b),g=g.replace(m[1],c);return g}});
(function(g){g.fn.typeWatch=function(c){function e(d){if("TEXT"==d.type.toUpperCase()||"TEXTAREA"==d.nodeName.toUpperCase()){var a={timer:null,text:g(d).val().toUpperCase(),cb:f.callback,el:d,wait:f.wait};f.highlight&&g(d).focus(function(){this.select()});var c=function(d){var c=a.wait,e=!1;13==d.keyCode&&"TEXT"==this.type.toUpperCase()&&(c=1,e=!0);clearTimeout(a.timer);a.timer=setTimeout(function(){var d=e,c=g(a.el).val();if(c.length>f.captureLength&&c.toUpperCase()!=a.text||d&&c.length>f.captureLength)a.text=
c.toUpperCase(),a.cb(c)},c)};g(d).keydown(c).bind("paste",null,function(a){a.which||c(this)})}}var f=g.extend({wait:750,callback:function(){},highlight:!0,captureLength:2},c);return this.each(function(){e(this)})}})(jQuery);
(function(g){function c(c){var d;return c&&c.constructor==Array&&3==c.length?c:(d=/rgb\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*\)/.exec(c))?[parseInt(d[1]),parseInt(d[2]),parseInt(d[3])]:(d=/rgb\(\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*,\s*([0-9]+(?:\.[0-9]+)?)\%\s*\)/.exec(c))?[2.55*parseFloat(d[1]),2.55*parseFloat(d[2]),2.55*parseFloat(d[3])]:(d=/#([a-fA-F0-9]{2})([a-fA-F0-9]{2})([a-fA-F0-9]{2})/.exec(c))?[parseInt(d[1],16),parseInt(d[2],16),parseInt(d[3],16)]:
(d=/#([a-fA-F0-9])([a-fA-F0-9])([a-fA-F0-9])/.exec(c))?[parseInt(d[1]+d[1],16),parseInt(d[2]+d[2],16),parseInt(d[3]+d[3],16)]:/rgba\(0, 0, 0, 0\)/.exec(c)?e.transparent:e[g.trim(c).toLowerCase()]}g.each("backgroundColor,borderBottomColor,borderLeftColor,borderRightColor,borderTopColor,color,outlineColor".split(","),function(e,d){g.fx.step[d]=function(a){if(!a.colorInit){var e;e=a.elem;var f=d,h;do{h=g.curCSS(e,f);if(""!=h&&"transparent"!=h||g.nodeName(e,"body"))break;f="backgroundColor"}while(e=e.parentNode);
e=c(h);a.start=e;a.end=c(a.end);a.colorInit=!0}a.elem.style[d]="rgb("+[Math.max(Math.min(parseInt(a.pos*(a.end[0]-a.start[0])+a.start[0]),255),0),Math.max(Math.min(parseInt(a.pos*(a.end[1]-a.start[1])+a.start[1]),255),0),Math.max(Math.min(parseInt(a.pos*(a.end[2]-a.start[2])+a.start[2]),255),0)].join()+")"}});var e={transparent:[255,255,255]}})(jQuery);
